# SPDX-FileCopyrightText: 2024 Mathieu Fenniak <mathieu@fenniak.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Release Artifacts

on:
  push:
    tags:
      - 'v*'

jobs:
  oci-container:
    runs-on: debian-ci-latest
    container:
      image: forgejo.kainnef.com/mfenniak/debian-latest-forgejo-runner@sha256:bf5d095672a3d43bf2a1aaf5b78fbb2f79c89a6a402150efb55634db6aa6fb7d
      options: --volume nix-forgejo-cache-public:/nix
    env:
      DOCKER_HOST: "tcp://forgejo-runner-dind:2375"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: https://github.com/cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31
      # install-nix-action by default uses {{ github.token }} and configures it as a github token; makes sense, but
      # we're running as a Forgejo action so Forgejo puts its own token in {{ github.token }} which GitHub can't
      # understand. So we replace github.com in the access-token field of the nix.conf file.
      - run: sed -i 's/github.com/codeberg.org/' /etc/nix/nix.conf
      - name: nix build docker
        run: nix build .#docker
      - name: load docker container
        run: gunzip < result | docker load
      - name: docker login
        run: echo "${{ secrets.TESTTRIM_PACKAGE_REGISTRY_PAT }}" | docker login codeberg.org -u mfenniak --password-stdin
      - name: push versioned docker container
        # GITHUB_REF_NAME should be the tag name (eg. v0.2.1), but the container is built without the leading v...
        run: docker push codeberg.org/testtrim/server:${GITHUB_REF_NAME#v}
      - name: docker tag and push latest
        run: docker tag codeberg.org/testtrim/server:${GITHUB_REF_NAME#v} codeberg.org/testtrim/server:latest && docker push codeberg.org/testtrim/server:latest
