# SPDX-FileCopyrightText: 2024 Mathieu Fenniak <mathieu@fenniak.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Rust Checks

on:
  push:
    # When new releases are tagged, both the tag and the push to main will build if we just do `on: [push]` -- so
    # instead we filter to just branch pushes which should disable the second build on the tag.
    branches:
      - '**'

jobs:
  rust-checks:
    runs-on: docker
    container:
      options: --volume nix-forgejo-cache-public:/nix

    services:
      pgsql:
        image: postgres:17@sha256:fe4efc6901dda0d952306fd962643d8022d7bb773ffe13fe8a21551b9276e50c
        env:
          POSTGRES_USER: testtrim
          POSTGRES_PASSWORD: testtrim

    env:
      DATABASE_URL: postgres://testtrim:testtrim@pgsql/testtrim
      TESTTRIM_DATABASE_URL: postgres://testtrim:testtrim@pgsql/testtrim

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: apt-get update && apt-get install -y sudo awscli postgresql-client # install-nix-actions requires `sudo`...
      - name: verify pgsql service is available
        run: timeout 30 bash -c 'while ! psql $DATABASE_URL -c "SELECT 1"; do sleep 1; done'
      - uses: https://github.com/cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      # install-nix-action by default uses {{ github.token }} and configures it as a github token; makes sense, but
      # we're running as a Forgejo action so Forgejo puts its own token in {{ github.token }} which GitHub can't
      # understand. So we replace github.com in the access-token field of the nix.conf file.
      - run: sed -i 's/github.com/codeberg.org/' /etc/nix/nix.conf
      - name: sqlx migrate
        run: nix develop .# --command sqlx migrate run --source ./db/postgres/migrations
      - name: cargo build
        run: nix develop .# --command cargo build
      - name: run tests
        run: nix develop .# --command cargo nextest run
        env:
          RUST_COVERAGE_SPECIMEN_PAT: ${{ secrets.RUST_COVERAGE_SPECIMEN_PAT }}
      - name: verify clippy warning-free
        run: nix develop .# --command cargo clippy -- -D warnings
      - name: verify clippy on tests warning-free
        run: nix develop .# --command cargo clippy --tests -- -D warnings
      - name: verify rust format correct
        run: nix develop .# --command cargo fmt --all -- --check
      - name: copyright checks
        run: nix develop .# --command reuse lint
