# SPDX-FileCopyrightText: 2024 Mathieu Fenniak <mathieu@fenniak.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Rust Checks

on:
  push:
    # When new releases are tagged, both the tag and the push to main will build if we just do `on: [push]` -- so
    # instead we filter to just branch pushes which should disable the second build on the tag.
    branches:
      - '**'

jobs:
  rust-checks:
    runs-on: debian-latest
    container:
      options: --volume nix-forgejo-cache-public:/nix

    services:
      pgsql:
        image: postgres:17@sha256:79c927b43c8bf2fc1e78b7f4badb394237ee0001032324ef015da562e57a5dcd
        env:
          POSTGRES_USER: testtrim
          POSTGRES_PASSWORD: testtrim

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: apt-get update && apt-get install -y sudo postgresql-client # install-nix-actions requires `sudo`...
      - name: verify pgsql service is available
        env:
          DATABASE_URL: postgres://testtrim:testtrim@pgsql/testtrim
        run: timeout 30 bash -c 'while ! psql $DATABASE_URL -c "SELECT 1"; do sleep 1; done'
      - uses: https://github.com/cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      # install-nix-action by default uses {{ github.token }} and configures it as a github token; makes sense, but
      # we're running as a Forgejo action so Forgejo puts its own token in {{ github.token }} which GitHub can't
      # understand. So we replace github.com in the access-token field of the nix.conf file.
      - run: sed -i 's/github.com/codeberg.org/' /etc/nix/nix.conf
      - name: .sqlx verify clean & correct
        env:
          DATABASE_URL: postgres://testtrim:testtrim@pgsql/testtrim
        run: |
          nix develop .# --command sqlx migrate run --source ./db/postgres/migrations
          nix develop .# --command cargo sqlx prepare -- --tests
          if [ -z "$(git status --porcelain)" ]; then
            echo "Clean working directory. 👍"
          else
            echo "sqlx prepare resulted in an unclean working directory; run 'cargo sqlx prepare' and commit changes"
            git status
            exit 1
          fi
      - name: cargo build
        run: nix develop .# --command cargo build
      - name: run tests
        env:
          TESTTRIM_UNITTEST_PGSQL_URL: postgres://testtrim:testtrim@pgsql/testtrim
          RUST_COVERAGE_SPECIMEN_PAT: ${{ secrets.RUST_COVERAGE_SPECIMEN_PAT }}
        run: nix develop .# --command cargo nextest run
      - name: verify clippy warning-free
        run: nix develop .# --command cargo clippy -- -D warnings
      - name: verify clippy on tests warning-free
        run: nix develop .# --command cargo clippy --tests -- -D warnings
      - name: verify rust format correct
        run: nix develop .# --command cargo fmt --all -- --check
      - name: copyright checks
        run: nix develop .# --command reuse lint
