# SPDX-FileCopyrightText: 2024 Mathieu Fenniak <mathieu@fenniak.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[test-groups]
serial-integration = { max-threads = 1 }

[[profile.default.overrides]]
# Note that these tests also implement internal locking to guarantee success -- so both approaches do the same thing.
filter = 'test(coverage::postgres_sqlx::) or test(coverage::testtrim_api::)'
test-group = 'serial-integration'

[profile.default]
slow-timeout = { period = "30s", terminate-after = 4 }
